### ISSUE TITLE
Wrong benchmarks

### ISSUE THREAD

**Issue by viswanathtadi** [adharshkamath/Mathy-Compiler#8]
Some of the bench marks are using out of scope variables for array indexing.

**Comment by adharshkamath** [comment]
Hi! Thanks for creating the issue. Can you please specify which benchmarks are accessing out of bounds memory?

**Comment by viswanathtadi** [comment]
Inside 1st forall in gemver.txt,
A[i][j] has j out of scope as j iterates for the sigma on rhs.

**Comment by adharshkamath** [comment]
I've made the correction through 0ca27ad. Thanks for pointing it out!
